# Grid Settings
dim_x: 50
dim_y: 50
dim_z: 3
spacing: 0.2
origin: [0, 0, 0]
nearfield_dist: 4
advanced: True

# Sensor Coverage Settings
conditions:
  N1: 2
  N2: 2
  N6: 2
  N7: 2
  N8: 2

# Z-Slice Settings
slice:
  number: 2
  distance: 0.35